In [32]:
import numpy as np
import time

In [19]:



def text_to_labels(letters, text):
    return list(map(lambda x: letters.index(x), text))

def __data_generation( ids):
    """Generates data containing batch_size samples"""
    print(ids)
    size = len(ids)
    CHARS = " ABCDEFIJLMNOSTVWabcdefghijklmnopqrstuvwxyz"
   
    Y = np.zeros([size,32])
   

    # Generate data
    for i, id_ in enumerate(ids):
        
        len_text = len("hello")
        Y[i, :len_text] = \
            text_to_labels(CHARS, "hello")
        print(Y[:,:7])
def run( index):
    """Generate one batch of data"""
    ids=range(0,100)
    indexes = np.arange(len(ids))
    np.random.shuffle(indexes)
    print(indexes)
    indexe = indexes[index *
                           64:(index + 1) * 64]

    ids = [ids[k] for k in indexe]

    __data_generation(ids)

    

In [20]:
run(1)

[77 21 59 62 89 10 22 86 50 75 63 85 91 45  3 46 13 18 48 16 57 54 23 15
 38 73  4  6  7 14 43 72  5 30 51 37 74 66  9 32 95 70 64 67 98 17 25 65
 80 71 99 76 20 35  8 93 87  0 34 84 33 31 58 82 92 78 44 68 79 29 88 12
  1 27 39 56 26 53 24 90 60 97 42 36 83  2 47 96 28 11 19 69 40 41 52 81
 94 49 55 61]
[92, 78, 44, 68, 79, 29, 88, 12, 1, 27, 39, 56, 26, 53, 24, 90, 60, 97, 42, 36, 83, 2, 47, 96, 28, 11, 19, 69, 40, 41, 52, 81, 94, 49, 55, 61]
[[24. 21. 28. 28. 31.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0

In [69]:
def edit_distance(word1, word2):
    len1 = len(word1);
    len2 = len(word2);
    dp = np.zeros((len1 + 1,len2 + 1))
    for i in range(len1 + 1):
        dp[i][0] = i;     
    for j in range(len2 + 1):
        dp[0][j] = j;
    print(dp)
    for i in range(1, len1 + 1):
        for j in range(1, len2 + 1):
            delta = 0 if word1[i-1] == word2[j-1] else 1
            print(i)
            print(j)
            
            dp[i][j] = min(dp[i - 1][j - 1] + delta, min(dp[i-1][j] + 1, dp[i][j - 1] + 1))
            print(dp[i][j])
    print(dp)
    return dp[len1][len2]

In [70]:
start_ = time.time()
# for i in range(6000):
edit_distance("appear","app")
end_ = time.time()
end_-start_

[[0. 1. 2. 3.]
 [1. 0. 0. 0.]
 [2. 0. 0. 0.]
 [3. 0. 0. 0.]
 [4. 0. 0. 0.]
 [5. 0. 0. 0.]
 [6. 0. 0. 0.]]
1
1
0.0
1
2
1.0
1
3
2.0
2
1
1.0
2
2
0.0
2
3
1.0
3
1
2.0
3
2
1.0
3
3
0.0
4
1
3.0
4
2
2.0
4
3
1.0
5
1
4.0
5
2
3.0
5
3
2.0
6
1
5.0
6
2
4.0
6
3
3.0
[[0. 1. 2. 3.]
 [1. 0. 1. 2.]
 [2. 1. 0. 1.]
 [3. 2. 1. 0.]
 [4. 3. 2. 1.]
 [5. 4. 3. 2.]
 [6. 5. 4. 3.]]


0.00812840461730957

In [346]:
a=np.array([43,43,43,7,43,4,43,11,43,43,11,11,11,43,11,43,43,43,43,14,43,43])
chars = np.array(list("abcdefghijklmnopqrstuvwxyz-----------------------------------"))

In [347]:
def decode_predict_ctc(lables,chars):
#     lables = np.argmax(out[0],axis=1)
    #去掉重复数字
    diff = lables[1:]-lables[:-1]
    rept = np.where(diff==0)[0]
    lables = np.delete(lables,rept)
    #去掉代表null的数字
    lables_del = np.where(lables==43)[0]
    lables = np.delete(lables,lables_del)
    pre_txt = "".join(chars[lables])
    return pre_txt

In [351]:
def decode_predict_ctc2(lables,chars):
    txt = "".join(chars[lables])
    #去掉重复字符 然后 去掉代表null的字符
    pre_txt = re.sub("(.)\\1+|-", "\\1", txt)
    return pre_txt

In [352]:
start_ = time.time()
for i in range(10000):
    pre_txt = decode_predict_ctc(a,chars)
end_ = time.time()
print("time: ",end_-start_)
print(chars[a])
print(pre_txt)

time:  0.36920666694641113
['-' '-' '-' 'h' '-' 'e' '-' 'l' '-' '-' 'l' 'l' 'l' '-' 'l' '-' '-' '-'
 '-' 'o' '-' '-']
helllo


In [353]:
start_2 = time.time()
for i in range(10000):
    pre_txt_2 = decode_predict_ctc2(a,chars)
end_2 = time.time()
print("time: ",end_2-start_2)
print(chars[a])
print(pre_txt)

time:  0.13443374633789062
['-' '-' '-' 'h' '-' 'e' '-' 'l' '-' '-' 'l' 'l' 'l' '-' 'l' '-' '-' '-'
 '-' 'o' '-' '-']
helllo
